### ISSUE TITLE
Escaped characters in Trello

### ISSUE THREAD

**Issue by jacobmarshall** [bugsnag/bugsnag-notification-plugins#106]
![Screenshot](http://i.imgur.com/3Td7mOS.png)

**Comment by snmaynard** [comment]
Did this get fixed on trellos end @jacobmarshall or still an issue for you?

**Comment by jacobmarshall** [comment]
I'm not too sure actually. I don't work at the company that used Trello as a Bugsnag integration. I'll do a quick check for you :)

I don't recall getting an email from Trello either... I'll double check that though.

**Comment by snmaynard** [comment]
@jacobmarshall you got a new gig?

**Comment by jacobmarshall** [comment]
Heck yeah, started on Tuesday :)

**Comment by snmaynard** [comment]
Awesome! Congrats!

**Comment by jacobmarshall** [comment]
Thanks @snmaynard :)

It would seem Trello did reply, but only to tell me that they've forwarded the email to the dev team. Since then, no other contact has been made.

I'll see if I can try and replicate the issue right now.

**Comment by jacobmarshall** [comment]
![Screenshot](https://www.dropbox.com/s/oquj8okoin4be0t/Screenshot%202015-01-10%2013.56.16.png?dl=0)

Still an issue apparently :/

**Comment by jacobmarshall** [comment]
I don't see how this can be a Bugsnag related issue though. All other integrations handle the same way... I can surely update this issue if/when Trello get back to me.

**Comment by jacobmarshall** [comment]
Weird... I was giving an demonstration of Bugsnag's integrations, and I selected GitHub (as an example), and it looks like GitHub does the same thing as Trello when using the same Bugsnag error.

[See here...](https://github.com/jacobmarshall/ducksar.se/issues/1)

**Comment by snmaynard** [comment]
Is this still an issue jacob? We released our replacement issue trackers the other day so everything has been rewritten on our side. Just closing up all our open issues on the old system and saw this. If its still causing you an issue can you ping a support request through? We should be able to solve it for you!
