### ISSUE TITLE
[LiquidPlanner] Error 500

### ISSUE THREAD

**Issue by jacobmarshall** [bugsnag/bugsnag-notification-plugins#112]
@mkiestmcfarland

Here is the response dump from SuperAgent... https://gist.github.com/jacobmarshall/ba77e54dfebe759b6313

I'm wondering if this is a fault in the integration (unlikely), something I'm doing, or a fault on LiquidPlanner's end (also unlikely, but unknown).

As far as I'm aware, the API is always on... and I am certain my email & password are correct, but whatever I try, I always get the same error.

**Comment by snmaynard** [comment]
We have the liquidplanner stuff all working in our new system after the plugins have all been rewritten so this seems fixed now!
