### ISSUE TITLE
Make Assembla Example URL less confusing

### ISSUE THREAD

**Issue by jessicard** [bugsnag/bugsnag-notification-plugins#118]
From support: "The example should probably not be a full URL, I didn't see that it was parameterized"

**Comment by kattrali** [comment]
Does this just mean to remove the protocol (https) from the [example description URL](https://github.com/bugsnag/bugsnag-notification-plugins/blob/master/plugins/assembla/config.json#L14)?

**Comment by jacobmarshall** [comment]
I believe that it means that the `space` config is actually asking for the `:space_name` parameter, not a URL. The example is a full url - and in this case it's hard to make out exactly what the config is actually asking for.

The actual integration specifies the API url [on line 6](https://github.com/bugsnag/bugsnag-notification-plugins/blob/master/plugins/assembla/index.coffee#L6).

**Comment by snmaynard** [comment]
I've just made a change to fix this - should go out soon!
