### ISSUE TITLE
Investigate how to become an official Hall integration

### ISSUE THREAD

**Issue by kpinedok** [bugsnag/bugsnag-notification-plugins#136]
Integrating Bugsnag with Hall is a messy process - it's buried and unclear. 

Expected: When you click "Add Integrations" in Hall, you should see a Bugsnag logo in the list of available integrations. When you click on it, it should lead you to a page that says "How to Integrate Bugsnag with Hall." This page should give a small Introduction that briefly explains what Bugsnag is and what the integration does, and provide the Group API token. 

Actual: Bugsnag doesn't appear in the list of available integrations. Instead you have to click a big gray question mark labeled "other" and then click "Get Started" under Build your Own. This lands on a generic integration page that says "How to Integrate your Service with Hall."

**Comment by jacobmarshall** [comment]
This is probably a little obsolete now that Atlassian have bought Hall.

**Comment by kpinedok** [comment]
We're not working on this right now, but thanks for looking into it @jacobmarshall!
