### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-notification-plugins#138]
We need to investigate how to get push notifications to ios/android working.

**Comment by xavierhb** [comment]
@snmaynard @Nowaker @jacobmarshall Added a new [pull request] (https://github.com/bugsnag/bugsnag-notification-plugins/pull/184) to integrate a plugin to send push notifications with (Pushed)[https://pushed.co]. Good thing is that Pushed is completely free. https://github.com/bugsnag/bugsnag-notification-plugins/pull/184

**Comment by xavierhb** [comment]
@snmaynard @Nowaker @jacobmarshall Just let you know that the pull request has been merged, you can now get push notifications every time there's a new exception on Bugsnag. :)

**Comment by jacobmarshall** [comment]
Cheers @xavierhb, really nice job.
