### ISSUE TITLE
Add support for getflow.com

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-notification-plugins#159]

**Comment by alainmeier** [comment]
:+1:

**Comment by jacobmarshall** [comment]
I cannot for the life of me find their API docs... I may need to inspect Chrome dev tools networking tab for a while...

**Comment by jacobmarshall** [comment]
It may be worth looking at [this](http://feedback.getflow.com/forums/214911-flow/suggestions/4207932-public-api)... apparently they don't have a public api yet :disappointed:

**Comment by snmaynard** [comment]
We've moved over to a new system for notifications and we have an internal ticket for this. The good news is it shouldn't take us much longer to get this shipped so it should be coming soon!

Closing this issue as this repo is being retired.
