### ISSUE TITLE
Add support for Done Done

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-notification-plugins#160]

**Comment by jjulian** [comment]
I've started the DoneDone integration, and I think the code looks good, but I'm having trouble testing. See my fork at https://github.com/jjulian/bugsnag-notification-plugins

    $ coffee index.coffee --subdomain=example --projectId=123 --username=jjulian --apitoken=SECRET --defaultFixerId=99 --defaultTesterId=99 --defaultPriorityId=1 --spike

    events.js:72
    throw er; // Unhandled 'error' event
             ^
    Error: incorrect header check
      at Zlib._binding.onerror (zlib.js:295:17)

I'm not sure how to debug this. Help?

**Comment by snmaynard** [comment]
It seems like you are getting a gzipped response or you are assuming you are getting a gzipped response from the server. This [stackoverflow](http://stackoverflow.com/questions/19438884/incorrect-header-check-when-using-zlib-in-node-js) may be useful - but i couldnt see anything in their api docs that mentioned gzipping
