### ISSUE TITLE
Use OAuth for BitBucket

### ISSUE THREAD

**Issue by ConradIrwin** [bugsnag/bugsnag-notification-plugins#165]

**Comment by jacobmarshall** [comment]
Not that it matters, but I assume that you will have to migrate the data, and use the user/pass auth to generate an OAuth access token, right?

**Comment by ConradIrwin** [comment]
That's what we did for the Github migration. Otherwise we can just leave support for both in the plugin, but only have the field for auth token in the UI.

**Comment by snmaynard** [comment]
Oauth is going to be rolled out for all plugins in the future! Closing this as this repo is going away
