### ISSUE TITLE
Add support for Serena TeamTrack Issue Tracking

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-notification-plugins#171]
http://pvcs.synergex.com/products/serena_team_track.aspx

I couldn't find API docs anywhere

**Comment by snmaynard** [comment]
We've moved over to a new system for notifications and we have an internal ticket for this. The good news is it shouldn't take us much longer to get this shipped so it should be coming soon!

Closing this issue as this repo is being retired.
