### ISSUE TITLE
Add support for Wrike Integration

### ISSUE THREAD

**Issue by snyfer** [bugsnag/bugsnag-notification-plugins#182]
Would be nice if you could integrate WRIKE.COM as an Issue Tracking Tool for bugsnag ... 

KR
Patrick

**Comment by snmaynard** [comment]
We've moved over to a new system for notifications and we have an internal ticket for this. The good news is it shouldn't take us much longer to get this shipped so it should be coming soon!

Closing this issue as this repo is being retired.
