### ISSUE TITLE
Configure issue tracker by severity level

### ISSUE THREAD

**Issue by puffin** [bugsnag/bugsnag-notification-plugins#185]
It would be great to be able to configure issue tracker to only be sent for bugs with certain severity levels. We might want github issue only for errors and not for warnings or info notifications, for example.

**Comment by jessicard** [comment]
Hey @puffin! This is actually on our roadmap for the future. I'm going to go ahead and close this issue, as it wouldn't be something we do in this repo, but in our actual dashboard. Thanks!
