### ISSUE TITLE
Support for VictorOps

### ISSUE THREAD

**Issue by jessicard** [bugsnag/bugsnag-notification-plugins#187]
Add team notification support for VictorOps

**Comment by davejlong** [comment]
@jessicard there is already a closed [pull request](https://github.com/bugsnag/bugsnag-notification-plugins/pull/188) for VictorOps support. I'm hoping that the Bugsnag guys will deploy it soon. Once it's setup, I have a support request in with VO to add documentation to their wiki.

**Comment by jessicard** [comment]
@davejlong Perfect! Thanks for the PR. I'll get this released today.
