### ISSUE TITLE
Add support to Team Foundation Server 

### ISSUE THREAD

**Issue by ChrisKotars** [bugsnag/bugsnag-notification-plugins#192]
https://www.visualstudio.com/en-us/products/tfs-overview-vs.aspx
:

**Comment by jacobmarshall** [comment]
I'll take a look as soon as I've submitted a few PRs I still need to push.

**Comment by jacobmarshall** [comment]
Bare with me with this one. I've tried once already to install this thing. What a beast.

**Comment by snmaynard** [comment]
We've moved over to a new system for notifications and we have an internal ticket for this. The good news is it shouldn't take us much longer to get this shipped so it should be coming soon!

Closing this issue as this repo is being retired.
