### ISSUE TITLE
Test with GitLab 8

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-notification-plugins#197]

**Comment by jacobmarshall** [comment]
Been meaning to set an instance up, I can give it a go.
On Thu, 8 Oct 2015 at 2:30 PM Simon Maynard <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-notification-plugins/issues/197>.
>
-- 
Regards,
Jacob

*Email:* jacob@manage.net.nz
*Phone:* (+64) 21 026 940 83

**Comment by jacobmarshall** [comment]
LFGTM

Tested on both self hosted, and GitLab.com.

<img width="1440" alt="screenshot 2015-10-09 18 56 36" src="https://cloud.githubusercontent.com/assets/4710291/10386868/839b6f36-6eb8-11e5-8a98-8fc19236bd95.png">
<img width="1440" alt="screenshot 2015-10-09 18 57 12" src="https://cloud.githubusercontent.com/assets/4710291/10386869/83a0436c-6eb8-11e5-9df1-0411240b751d.png">

**Comment by snmaynard** [comment]
Thanks jacob!
