### ISSUE TITLE
Datadog support

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-notification-plugins#27]

**Comment by coop** [comment]
I'd be interested in helping this through, what would be required?

**Comment by snmaynard** [comment]
I would imagine datadog would look fairly similar to our chat plugins (like Slack or Hipchat) so I would take a look at one of those plugins for inspiration. You'd just have to create a datadog directory with the config and index.coffee appropriately adjusted for datadog. You can see how to contribute at https://github.com/bugsnag/bugsnag-notification-plugins#writing-your-plugin and how to test it at https://github.com/bugsnag/bugsnag-notification-plugins#testing-your-plugin

If you get started and have any specific questions - let me know!

**Comment by snmaynard** [comment]
Datadog support was released some time ago so closing!
