### ISSUE TITLE
Phabricator issue tracking support

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-notification-plugins#33]
Add support for [Phabricator](http://phabricator.org/) tasks (the tasks part of Phabricator is called Maniphest).

Api docs:
http://www.phabricator.com/docs/phabricator/#conduit

**Comment by loopj** [comment]
+10

@jacobmarshall if you are looking for a new fun project, this might be a good one! :)

**Comment by jacobmarshall** [comment]
Pretty busy at the moment, but this is todays goal. Apologies for the delay @loopj.

**Comment by MarkVaughn** [comment]
Is there an update on this @jacobmarshall ?

**Comment by jacobmarshall** [comment]
Sadly not yet. I've been overrun with work at the moment. As soon as I get round to working on this, I will update this issue. Sorry to the wait, I only wish I had more time.

**Comment by myanimal** [comment]
+1
@jacobmarshall here, have some of my time :)

**Comment by snmaynard** [comment]
We've moved over to a new system for notifications and we have an internal ticket for this. The good news is it shouldn't take us much longer to get this shipped so it should be coming soon!

Closing this issue as this repo is being retired.
