### ISSUE TITLE
Pivotal requester should not be set automatically 

### ISSUE THREAD

**Issue by jtuttlefiksu** [bugsnag/bugsnag-notification-plugins#46]
When creating a Pivotal story from within bugsnag, the requester is set automatically to the user whose API key was used to configure the Pivotal plugin. If possible, it might be better to leave the requester blank on story creation (we would certainly prefer it that way). Simon suggested this may be possible by sending a blank `requester_id` value in the POST request to the Pivotal API.

This isn't a huge issue and may be desired behavior. Just something to consider. Thanks!

**Comment by snmaynard** [comment]
We're planning on doing this very soon. We've just finished rewriting our plugins with this in mind - and soon a settings revamp should hit the site. Once that is done we are going to add a feature to allow people to auth with their issue trackers and clicking create issue will create the issue as that user!

Closing this as we have an internal ticket for it now and this repo is going away soon.
